version: "3.9"

services:
  mysql:
    image: mysql
    ports:
      - 127.0.0.1:3306:3306
    environment:
      - MYSQL_USER=changeme
      - MYSQL_PASSWORD=changeme
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=changeme