version: "3.9"

services:
  api:
    build: .
    command: /bin/bash -c "npm run start:prod"
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - mynet

  mysql:
    image: mysql
    environment:
      - MYSQL_USER=changeme
      - MYSQL_PASSWORD=changeme
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_DATABASE=changeme
    networks:
      - mynet

networks:
  mynet: